[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Patrick Thomas <patrick-thomas@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.20"
assert_cmd = "0.10"
predicates = "1"